apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: cajun-navy
  labels:
    app: cajun-navy
  namespace: cajun-navy
spec:
  kafka:
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: '2.7'
      inter.broker.protocol.version: '2.7'
    version: 2.7.0
    storage:
      size: 1Gi
      deleteClaim: true
      class: rook-ceph-block
      type: persistent-claim
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
  entityOperator:
    topicOperator: {}
    userOperator: {}
  zookeeper:
    storage:
      class: rook-ceph-block
      deleteClaim: true
      size: 1Gi
      type: persistent-claim
    replicas: 3
